sudo: required
services:
  - docker


before_install:
  - docker build -t ashishdhawal/docker-multi -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ashishdhawal/docker-multi npm run test -- --coverage

after_success:
  - docker build -t ashishdhawal/doc-multi-client ./client
  - docker build -t ashishdhawal/doc-multi-nginx  ./nginx
  - docker build -t ashishdhawal/doc-multi-server ./server
  - docker build -t ashishdhawal/doc-multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin
  # Take those images & push those images to DockerHub
  - docker push ashishdhawal/doc-multi-client
  - docker push ashishdhawal/doc-multi-nginx
  - docker push ashishdhawal/doc-multi-server
  - docker push ashishdhawal/doc-multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: dock-multi
  env: DockMulti-env
  bucket_name: elasticbeanstalk-us-east-2-171912905752
  bucket_path: dock-multi
  on:
    branch: master
  access_key:  $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

